dfd bi
TUS-OSK/quantum-gomoku pull request #24
Opened 2024-08-17 08:34 UTC by oginoshikibu

2024-08-17 16:24 UTC, 1m-N00b submitted a review, later dismissed
LGTM

2024-08-18 07:35 UTC, oginoshikibu commented
> LGTM

これ、Draft PRなのでまだreview依頼出してない状態です。

2024-08-20 04:20 UTC, qq8244353 reviewed
# 質問
- Reset Passwordをしたら未ログイン状態になるのは嬉しくないと思っているんですけど何か理由がありますか？
- ユーザー削除は論理削除ですか？それともレコードの削除ですか？

## コメント
図からイメージした部分について書いておくので認識が違ったら教えてください！
- 仮登録の状態がないのはメールアドレスの情報など検証すべきものがないから
- 重複があると「すでにフレンドになっています」というメッセージが出るイメージ
- idは被らないようにしないと、ユーザー削除後フレンド情報が残って再度登録した知らない人がフレンドになったりするなあと思いました

2024-08-20 04:43 UTC, oginoshikibu commented
> * Reset Passwordをしたら未ログイン状態になるのは嬉しくないと思っているんですけど何か理由がありますか？
正しい認証処理を行わずにログイン状態にしたくない気持ちがあります。
認証プロセスを再度バックエンドで走らせておくことで、ログイン状態を外見上維持できると思いますが、現段階では必要ないかなと考えました。
リダイレクトをするだけなので、ユーザー管理周りが一通り整ってからでもよいかなという判断です。

> * ユーザー削除は論理削除ですか？それともレコードの削除ですか？

現時点ではレコード削除としています。
そのことを明示し、不足していたフレンドDBへの削除を追加しました。
 
> * 仮登録の状態がないのはメールアドレスの情報など検証すべきものがないから
「情報の有無」はDBレベルの話なのでDFDにはそこまで関係がなく、単に仮登録という状態をMVPで作らないから、という理由です。
実際に、user tableにはemailのカラムを持つ予定です。

> * 重複があると「すでにフレンドになっています」というメッセージが出るイメージ
yes

> * idは被らないようにしないと、ユーザー削除後フレンド情報が残って再度登録した知らない人がフレンドになったりするなあと思いました
そうですね……
MVPではtableのindex (increment)で一旦実装してもらおうかな～と思ってます

2024-08-20 07:45 UTC, qq8244353 requested changes
# コメントへの返答
> 正しい認証処理を行わずにログイン状態にしたくない気持ちがあります。

パスワードの更新をするためにはすでにログイン状態であるはずなので、再び認証する必要性がよくわかりません！複数のPCからログインしている状況でみたいな話でしょうか？

> そのことを明示し、不足していたフレンドDBへの削除を追加しました。

対応ありがとうございます！

> 「情報の有無」はDBレベルの話なのでDFDにはそこまで関係がなく、単に仮登録という状態をMVPで作らないから、という理由です。
実際に、user tableにはemailのカラムを持つ予定です。

emailを個人情報として持つ場合、そのメールアドレスが正しくなくても正式に登録されてしまうのはフローとして問題がある気がしています。メールアドレスの情報はおまけ程度で特に重要でないからそこの検証はしなくてよいという話なら納得できます。

> そうですね……
MVPではtableのindex (increment)で一旦実装してもらおうかな～と思ってます

認識すり合わせありがとうございます！

# 修正依頼
Search a Userのフレンド登録の図が壊れています。

2024-08-20 16:04 UTC, oginoshikibu commented
# コメント返信
> >正しい認証処理を行わずにログイン状態にしたくない気持ちがあります。
> パスワードの更新をするためにはすでにログイン状態であるはずなので、再び認証する必要性がよくわかりません！複数のPCからログインしている状況でみたいな話でしょうか？
 
 パスワード変更直後って、「新規パスワードでの認証」はしてなくないですか？？
ログイン状態を維持する場合でも
「パスワード変更リクエスト」-内部へ->（パスワード変更処理）→（ログイン処理）-外部へ→「変更成功」
 の方が自然かなと思いました。
ただ、そう考えているだけで明確に根拠があるわけではないです。

> >実際に、user tableにはemailのカラムを持つ予定です。
> emailを個人情報として持つ場合、そのメールアドレスが正しくなくても正式に登録されてしまうのはフローとして問題がある気がしています。メールアドレスの情報はおまけ程度で特に重要でないからそこの検証はしなくてよいという話なら納得できます。

メールアドレスを持たない場合、ユーザーが登録するものはどのようなものを想定していますか？
前提認識として、ユーザーが登録時に入力必須の情報は（ユニークな任意データ, パスワード）の2つだと思っています。
例えばユーザーネームをユニークとすれば運用可能だと思うのですが、①ユーザーネームの重複を許す仕様は十分考えられる②email認証はいつか必ず実装する、という2点のメリットが個人情報を持つという点よりも上回っている気がしています。

# 修正

> Search a Userのフレンド登録の図が壊れています。

修正しました。ありがとうございます！！

2024-08-21 03:28 UTC, qq8244353 requested changes
# コメント返信
> パスワード変更直後って、「新規パスワードでの認証」はしてなくないですか？？
ログイン状態を維持する場合でも
「パスワード変更リクエスト」-内部へ->（パスワード変更処理）→（ログイン処理）-外部へ→「変更成功」
の方が自然かなと思いました。
ただ、そう考えているだけで明確に根拠があるわけではないです。

ありがとうございます！いろいろ調べてみた結果、流れとしてはこのほうが適切だなと思いました。（実際の実装はパスワードを再設定されたらtokenをrevokeする処理が走る感じだと思っています）


> メールアドレスを持たない場合、ユーザーが登録するものはどのようなものを想定していますか？

ユーザー名をユニークにするのが自然だと思います。

>前提認識として、ユーザーが登録時に入力必須の情報は（ユニークな任意データ, パスワード）の2つだと思っています。

認識同じです。

> 例えばユーザーネームをユニークとすれば運用可能だと思うのですが、①ユーザーネームの重複を許す仕様は十分考えられる②email認証はいつか必ず実装する、という2点のメリットが個人情報を持つという点よりも上回っている気がしています。

結論としてemailをユニークな情報にして利用したいという風に解釈しました。
その場合、他人に自分のメールアドレスを使って登録されてしまい、自分のメールアドレスで登録できないような場合があると思っています。それを防ぐためにメールアドレスの検証をする必要があるわけです。
なので、「メールアドレスの検証が済んでいない」という状態（つまり仮登録の状態）があって、これは状態遷移図に入れるべきではないでしょうか？
なので解決策としては
- メールアドレスをユニークな情報として使わない
- 状態遷移図に仮登録の状態を入れる

のいずれかだと思っています。
メールアドレスをユニークな情報として使わない場合の状態遷移図としては現状問題がないと思っています。

# 修正依頼
変更がコミットされていません！

2024-08-21 11:24 UTC, oginoshikibu commented
# コメント返信

> ありがとうございます！いろいろ調べてみた結果、流れとしてはこのほうが適切だなと思いました。（実際の実装はパスワードを再設定されたらtokenをrevokeする処理が走る感じだと思っています）

調査めちゃめちゃ助かります……！！テキトーでよいので、次コメントするとき参考リンク貼っておいてもらえると助かります。
 
> 結論としてemailをユニークな情報にして利用したいという風に解釈しました。 その場合、他人に自分のメールアドレスを使って登録されてしまい、自分のメールアドレスで登録できないような場合があると思っています。それを防ぐためにメールアドレスの検証をする必要があるわけです。 なので、「メールアドレスの検証が済んでいない」という状態（つまり仮登録の状態）があって、これは状態遷移図に入れるべきではないでしょうか？ なので解決策としては
> 
> * メールアドレスをユニークな情報として使わない
> * 状態遷移図に仮登録の状態を入れる
> 
> のいずれかだと思っています。 メールアドレスをユニークな情報として使わない場合の状態遷移図としては現状問題がないと思っています。

めちゃくちゃその通りですね。ありがとうございます。
emailかユーザーネームかで悩みましたが、emailにして仮登録扱いにしようかなと思います。
理由は「MVPは外部公開しないので、アクシデントが起こりえない」からです。
拡張性を考えたときに、emailにしておくメリットがかなり大きく感じています。

修正としては登録プロセス部分を仮登録し、上部の説明にも追加しました。

# 修正依頼
> 変更がコミットされていません！

すみません、ありがとうございます！！謎にpush失敗してました……(´・ω・｀)

2024-08-21 11:45 UTC, qq8244353 submitted a review, later dismissed
対応いただきありがとうございました！

2024-08-21 11:47 UTC, qq8244353 commented
参考リンク（？）
https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-13#section-3.4

2024-08-28 05:32 UTC, RINNNNNNNNNNNNNNNNNN requested changes
API設計していて思ったんですけど、Check Passwordの欄は必要ないんですかね？
①ユーザーがパスワードを忘れる
②パスワード入力時に誤って認識とは違うパスワードを入力してしまう
MVPアプリ実装時に起こりうるのは②だと思うので、とりあえずRegister Password時にパスワードを二回入力してもらうようにすべきかなと感じました

2024-08-28 14:56 UTC, oginoshikibu commented
# @RINNNNNNNNNNNNNNNNNN へのコメント返信

いくつか話が混ざってそうなので、少し分割して回答しますね。

> API設計していて思ったんですけど、Check Passwordの欄は必要ないんですかね？

ここの「欄」とは何のことでしょうか？

1. 新たなDFD
1. 追加で「Check Password」というプロセスを追加すべき
1. 画面上での入力欄を指している

1, 2の場合、現状のDFD図のどの部分に問題があって、どう変更すべきなのかがいまいち理解できませんでした。特に「Check Password」という言葉が「どういう状態のパスワードをどうcheckするのか」といった意が汲めず、分からなかったです……。可能であればもう少し指摘を具体的にして頂けると助かります！！

3の場合は、おそらくDFDで考える範疇を超えているため、このPRを超えた部分の仕様の話かと思います。

> ①ユーザーがパスワードを忘れる

この問題についてはMVPではサポートしない設計になっています。
register/loginの図にも表記してある通り、全ユーザーは仮登録扱いのままとなります。
つまり事前に認証することは一度もないため、パスワードを忘れたと主張するユーザーが本当にそのユーザーなのかを確認する手立ては、システム上存在しないことになっています。
- ユーザー登録した上で保持する情報はフレンド情報のみでゲーム部分と完全に分離されているためUXへの影響は少ない
- 最低限主導でメール特別対応を行えばよい
- そもそも外部公開を行わない

辺りが、MVPではこのような仕様でよい根拠でしょうか

> ②パスワード入力時に誤って認識とは違うパスワードを入力してしまう

こちらも意味が2つ取れたので、両方回答を用意しておきます。（おそらく後者を指してそう……？？）

## Login時に入力したパスワードという意

恐らく認証のプロセスから失敗時のフローが無いことを指しているのかなと思います。
この指摘は全くその通りで、正常系のみこのDFDでは記載しています。
そのため、認証の失敗やDBでのerrorなどのフロー全て記載されておりません。
本当は記載した方がよいのですが、手が回りきらず……

## Resister時に入力したパスワードという意

これはひとつ前の①と同様の議論だと認識しています。
パスワードのみを認証の手段となっている都合上、誤った登録をした場合は復元不可能になるかと思います。

> MVPアプリ実装時に起こりうるのは②だと思うので、とりあえずRegister Password時にパスワードを二回入力してもらうようにすべきかなと感じました

「2回入力する」といった動作はフロントエンドのバリデーションの話になってくるので、DFDの管轄外となっています。

2024-08-28 23:10 UTC, tamachika reviewed
delete / change password
の下にある「パスワード変更」は「パスワード削除」って書いた方がいい気がした！(レビューってこんな感じでおけ？)

2024-08-29 10:52 UTC, oginoshikibu commented
# @tamachika コメント返信

> delete / change password の下にある「パスワード変更」は「パスワード削除」って書いた方がいい気がした！(レビューってこんな感じでおけ？)

修正しました！！（パスワードではなくユーザー削除ですが……）

2024-08-30 03:19 UTC, RINNNNNNNNNNNNNNNNNN submitted a review, later dismissed
了解しました！説明ありがとうございます

2024-09-01 10:53 UTC, tamachika commented
Get friends list
で、「フレンドのid」と「フレンド情報」別々にとらなくてもいいのかなと思った。

2024-09-01 19:23 UTC, oginoshikibu commented
@tamachika 
> Get friends list
> で、「フレンドのid」と「フレンド情報」別々にとらなくてもいいのかなと思った。

（「フレンドid」ではなく「フレンドユーザーリスト」と書かれている部分のこと……？？）
これは保存しているDBが別なので、明確に別のプロセスになるはずです！
DBが別かどうかという話であれば、基本別になっていると思いますが、DB設計の知識がないとちょっとむずいかもです

2024-09-22 12:49 UTC, tamachika approved these changes
お待たせしましたorz

2024-09-22 13:11 UTC, merged