状態遷移図
TUS-OSK/quantum-gomoku pull request #27
Opened 2024-08-20 14:25 UTC by azubiwa

### やったこと
状態遷移図の作成

### 問題点
・先手と後手をまとめて書くかどうか

### まだやっていないこと
・相手手番の待機
・両方が観察を使いきった時と盤面が全部埋まった時の対応

2024-08-20 15:40 UTC, oginoshikibu requested changes
全体的にとてもよく書けていると思います！！！MileStoneの設定を忘れずにお願いします！！
（mermaid、いいですね……僕も書き換えようかな）

## review内容について
先手後手区分する側に石を打つが抜けています
気づいたので書いちゃいました

## 先手後手について

状態遷移図は基本的に、仕様の自由度を除けば一意に決まるものだと思っています。
曖昧かもしれないな、と思った点は「何の状態遷移図なのか」（画面、片方のユーザー、2人のユーザー）というところです。
先手後手を区別しない側は片方のユーザー、する側は画面、の遷移図になっている気がしています。
一応目的が「フロントエンドの画面設計」なので、画面主体でよいかなと**少しだけ**思いましたが、正解が僕もわからないです……
状態遷移図を使うとわかりやすいんじゃない？は僕の発想で、慣例的なものをあまり知らないのですよね。
なので、えいやと決めてしまってよいと思います。

ただ、主体を明示的に示す必要はあると思います。
ドキュメント名はとりあえずの命名でUXにしてしまっているので、もし画面主体の場合は変更してもらえると助かります。（screen state transitionとかになるのかなあ……）

2024-08-20 15:40 UTC, oginoshikibu commented on docs/01.Frontend/01.UserExperience/README.md
> +    SENTE-->S_obs{"観測を行う"}
石を打つが抜けています
```suggestion
    SENTE-->S_stone{"石を打つ"}
    S_stone-->S_obs{"観測を行う"}
```

2024-08-20 15:40 UTC, oginoshikibu commented on docs/01.Frontend/01.UserExperience/README.md
> +    GOTE-->G_obs{"観測を行う"}
こちらも同様に石を打つが抜けています
```suggestion
    GOTE-->G_stnoe{"石を打つ"}
    G_stone-->G_obs{"観測を行う"}
```

2024-08-21 15:17 UTC, azubiwa commented
修正と引き分け部分の追加をしました。
盤面が埋まった時に観測をせず引き分けにしているのですが、1度観測してからの方が良さそうな気がします(盤面が埋まった状態で観測すれば勝敗が決まりそうなので)。

2024-08-21 16:06 UTC, oginoshikibu requested changes
ややこしいタスクをこなしてもらい、ありがとうございました！
とても良くできていると思います！！

# review内容について

先手後手番をそれぞれ書くことに悩んでいたようなので、サブルーチンとして切り出してみました。
reviewがものすごく見づらくなってしまい申し訳ないですが、ローカルにコピペするなりして確認してみてください！

切り出した部分をこちらで若干編集入れてしまったので、記載しておきます。
以下の項目がreview項目と思っていただければ……

## 1. 勝敗確認

勝敗判定のロジックについて、特に言及がなかったですが、ここで仮決めしてもよいと思います。
量子五目では両者同時に5目揃う可能性があるため、リスクある観測者側が有利になるようにしてみました。
全然変えてもらって構いません。

## 2. 命名規則を若干変更

状態が大文字スネークケーズ、分岐を小文字スネークケースに統一しました。
特に意図は無く、いつの間にか手が動いてしまいました……

# その他の修正依頼

フォルダ名の変更もお願いします！！

2024-08-21 16:06 UTC, oginoshikibu commented on docs/01.Frontend/01.UserExperience/README.md
> +
ゲーム画面であることを明示した方がよいと思います
```suggestion

## ゲームプレイ画面

```

2024-08-21 16:06 UTC, oginoshikibu commented on docs/01.Frontend/01.UserExperience/README.md
> +```
手番をサブルーチンとして切り出すのはどうでしょうか
```suggestion
```mermaid
graph TD;
    subgraph 手番のルーチン

        TEBAN["手番の処理"]
        AITEBAN["相手番（ゲーム続行）"]
        MY_WIN["勝利"]
        MY_LOSE["敗北"]
        MY_DRAW["引き分け"]


        TEBAN-->stone["石を打つ"]
        stone-->stone_cnt{"石の個数の確認"}
        stone_cnt-->|Ok| obs{"観測を行う"}
        obs-->|Yes| check{"勝敗判定を行う"}
        check-->|Unresolved| obs_cnt{"観測回数の確認"}

        obs_cnt-->|Ok| AITEBAN
        obs-->|No| AITEBAN
        obs_cnt -->|観測回数消費済み| MY_DRAW
        stone_cnt -->|盤面が埋まった| MY_DRAW
        check -->|自色が5連| MY_WIN  
        check -->|自色が4連以下 ∧ 相手色が5連| MY_LOSE
    end

    subgraph ゲームの流れ
        A("訪れる")-->B["ゲーム開始ボタンを押す"]
        B-->C["先手と後手を決める"]
        C-->SENTE
        SENTE["先手番"]
        GOTE["後手番"]

        SENTE-->sente_process{"先手番の処理"}
        sente_process-->|ゲーム続行| GOTE
        GOTE-->gote_process{"後手番の処理"}
        gote_process-->|ゲーム続行| SENTE

        DRAW["引き分け"]
        FIN["勝敗の表示"]
        END("ゲーム終了")

        sente_process & gote_process-->|観測回数消費済み or 盤面が埋まった| DRAW
        gote_process & sente_process-->|勝敗決定| FIN
        DRAW & FIN -->END
    end
```
```

2024-08-22 00:01 UTC, oginoshikibu commented
# コメント返信

> 修正と引き分け部分の追加をしました。 盤面が埋まった時に観測をせず引き分けにしているのですが、1度観測してからの方が良さそうな気がします(盤面が埋まった状態で観測すれば勝敗が決まりそうなので)。

確かに……🤔🤔
勝敗が決まるまで観測を繰り返す、とかでよいかもしれませんね！！

2024-08-22 16:34 UTC, azubiwa commented
サブルーチンにしました！

盤面が埋まった時は、どちらが観測をどのくらい残しているのかによって、判定方法がかなりややこしくなりそうなのでひとまず引き分けのままにしています。

2024-08-25 09:17 UTC, oginoshikibu requested changes
ありがとうございます！！とてもきれいにまとまっていると思います。

折角ここまで色々と考えてきたので、その内容を簡単でよいので書き残すとよいと思います。
ドキュメントの役割として、実装の指針となる「設計書」以外にも、なぜそのような仕様になっているかの「理由書」も実は含まれており、将来的にこちらが結構役に立ちます。

現状でもdiscordやPR上にちゃんと書き残してくれているのでとてもありがたいです！
項目ごとに一言程度でよいので、そう決めた背景・理由（「理由は特にない」も重要な情報です）を書き残しておきましょう。
僕がとりあえず思いついた項目しか書いていないので、勿論項目を増やしてもらって構いません！！

2024-08-25 09:17 UTC, oginoshikibu commented on docs/01.Frontend/01.ScreenStateTransition/README.md
> +    end
折角仕様について色々考えたので、軽く背景部分を書いておいてみましょうか！！

```suggestion
    end
    
## ゲーム仕様についての補足

### 観測時の勝敗条件について

このゲームでは1回の観測で、両者同時に勝利条件を満たすことがある。
その場合、この仕様では観測者が有利になるようにしてある。
理由としては……

### 盤面が埋まった時

現状盤面サイズは決まっていないが、最終的に石を打ち尽くして盤面が埋まる可能性がある。
このとき、この仕様では引き分け扱いとしている。
本家五目並べでは……
将来的には観測が余っている場合……

```

2024-08-25 23:45 UTC, 1m-N00b approved these changes
lgtm

こういうレビューって編集テキスト(今回ならREADME.md)をローカルに落として見るのが正解なのかな マーメイドなるダイアグラム作成ツール?の文法諸々知らないので[オンラインエディア](https://mermaid.live/edit)で見ときました。

2024-08-28 14:58 UTC, oginoshikibu commented
通話でも伝えましたが一応テキストでも残しておきます。
ここのrich diffのiconを押すと、git hub上でそのmdがどう表示されるか見ることが出来ます。

![image](https://github.com/user-attachments/assets/81e4a8e2-9df6-4264-8645-057bcc418c0b)

> こういうレビューって編集テキスト(今回ならREADME.md)をローカルに落として見るのが正解なのかな マーメイドなるダイアグラム作成ツール?の文法諸々知らないので[オンラインエディア](https://mermaid.live/edit)で見ときました。

2024-08-28 15:03 UTC, oginoshikibu approved these changes
LGTM！！完璧です！！！

QKや連珠をちゃんと参考資料としてどうすべきか候補を出し、その中でよさそうなものをちゃんと決め切る、というのをしっかりとやり遂げてもらいましたが、結構難しいことです。
とても見やすくまとまっていますし、mermaidにしたことで保守性もよく、後でこのドキュメントを見た人は泣いて喜ぶと思います。

2024-08-28 15:03 UTC, oginoshikibu commented on docs/01.Frontend/01.ScreenStateTransition/README.md
> +本家量子五目並べ（QuizKnock）でも、両者が同時に勝利条件を満たした時は観測者勝利となっている。
これ、めちゃめちゃいい補足だと思います！！！！！
裏どりはめんどくさいけど、とっても大事！！！！

2024-08-29 06:19 UTC, merged