issueとPRのテンプレートを作成
TUS-OSK/quantum-gomoku pull request #28
Opened 2024-08-20 17:52 UTC by 1m-N00b

fixed: #2 

markdownよりymlの方が良さそうだったのでymlで記述

2024-08-21 01:14 UTC, oginoshikibu requested changes
ありがとうございます！レビューに加えていくつか対応お願いします。

1. PRのtemplateが見当たらないです……
2. 次回からでよいので、ブランチの命名を[これ](https://github.com/TUS-OSK/quantum-gomoku/tree/develop/docs/0.HowToDev/02.DevProcess#%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E5%90%8D%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)に従ってもらえると助かります

# 補足
issueとPRの思想として、「issueは出来るだけ楽に、PRは詳細に書く」のが良いのかなと考えています。
なので、issueのいくつかの項目（特にfeat）は削除（任意？）してissue完了時の状態の記載などのみを必須化し、PR文に委託してしまう形でもよいのかなと思っています。
タスク開始時にDraft PRを出してもらうことをお願いしていますし……
どこまで削るかはPR文にもよるので、今回のreviewでは特に言及しませんでした。

2024-08-21 01:14 UTC, oginoshikibu commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +labels: ["bug"]
調査、ドキュメント、設計系のタスクもissueで管理するため、bug/feat以外の区分も欲しいです。
別建てで作るのがめんどくさいのであれば、全共通のざっくりとした枠組みにしてしまってもよいです。

2024-08-21 01:14 UTC, oginoshikibu commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +          - 例: fixed #123
必ずしも対象のissueを書く必要はないのかなと思っています。
勿論書いてくれた方がうれしくはあるのですが、これでバグレポートの手間が増えてしまうのを懸念している形です
```suggestion
```

2024-08-21 01:14 UTC, oginoshikibu commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +          - before/after(どのような変更かを画像や動画などで補足するとより良い)
TDDより、テストを書く指示文が欲しいです
```suggestion
        以下のようなことを添えて記述してください。
        - 期待される挙動
          - before/after(どのような変更かを画像や動画などで補足するとより良い)
          - どういったテストで検証されるか(可能であれば)
```

2024-08-21 01:14 UTC, oginoshikibu commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +          - 例: fixed #123
新規機能開発なので、issue numを書くことはあまりないと思います
```suggestion
        - issue number（強い依存関係がある場合は記載する）
          - 例: after #123
```

2024-08-21 01:14 UTC, oginoshikibu commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +        - その他(参考リンクや注意点や補足事項等)
同様にTDDより、テストを書く指示文が欲しいです
```suggestion
        以下のようなことを添えて記述してください。
        - 期待される挙動
          - before/after(どのような変更かを画像や動画などで補足するとより良い)
          - どういったテストで検証されるか(可能であれば)
```

2024-08-21 01:36 UTC, 1m-N00b commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +          - 例: fixed #123
例として挙げているだけで記述は任意なので問題ないかと

2024-08-21 01:36 UTC, 1m-N00b commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +labels: ["bug"]
> 調査、ドキュメント、設計系のタスクもissueで管理するため、bug/feat以外の区分も欲しいです。
これはfeature_request.ymlが担っていると思っている

2024-08-21 01:42 UTC, 1m-N00b commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +labels: ["bug"]
> 調査、ドキュメント、設計系のタスクもissueで管理するため、bug/feat以外の区分も欲しいです。
これはfeature_request.ymlが担っていると思っている。

2024-08-21 01:48 UTC, 1m-N00b commented
> PRのtemplateが見当たらないです……

これのfeature_request.ymlがほぼ同義と化してるからこれを、.github下に置くつもりでいた

> issueとPRの思想として、「issueは出来るだけ楽に、PRは詳細に書く」のが良いのかなと考えています。
なので、issueのいくつかの項目（特にfeat）は削除（任意？）してissue完了時の状態の記載などのみを必須化し、PR文に委託してしまう形でもよいのかなと思っています。

そこに関してはvalidationsをtrueにせず緩めればいいかなと思っている

2024-08-21 10:35 UTC, oginoshikibu requested changes
# コメント返信

> これのfeature_request.ymlがほぼ同義と化してるからこれを、.github下に置くつもりでいた

であればそのファイルを作ってからPRを出してほしいです。PRはmerge直前に出してほしくて、そうでない場合はDraft PRとしてください。

もし仮に別のPRで追加する予定であれば、タイトルの変更をお願いします

> そこに関してはvalidationsをtrueにせず緩めればいいかなと思っている

確かにそうですね。
ちょっと前のissue templateをイメージしていて、その場合記載されていると「書かなきゃ」と思ってしまうかなと思ったのですが、今はform形式で表示してくれるのですね。

2024-08-21 10:35 UTC, oginoshikibu commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +labels: ["bug"]
featで#22 みたいなもの（や、「学際での展示の相談」など）を扱うと、かなりいびつだと思うのですが、どうでしょうか？
タスク管理のすべてをissueで行う都合上、PRが発生するようなもののみfeatとするのが健全かなと考えています

2024-08-21 10:35 UTC, oginoshikibu commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +          - 例: fixed #123
特に変更/コメントなくresolvedになっているのですが、どういう意図でしょうか？

2024-08-21 11:52 UTC, 1m-N00b commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +labels: ["bug"]
自分的にはそれらの情報ってそれこそMTGのときにするなりのチャットや質問の方が円滑だと思っていて、そこでfeatまで進めて始めてgithub上にタスクとしてあげると思ってた。特に後者の情報とかなら尚更クローズドでした方が良いと思う
だからそれら全てgithub管理する必要はないと思ってるかな自分は
何よりそれら議論が増えそうなものだとgithub見にくくない?

2024-08-21 11:52 UTC, 1m-N00b commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +          - 例: fixed #123
https://github.com/TUS-OSK/quantum-gomoku/pull/28#discussion_r1724148955

あれ？ここで書き換えてたからそれでいいかと思ってコミットしたけど反映されてないのかな🤔

2024-08-21 12:07 UTC, 1m-N00b commented
> であればそのファイルを作ってからPRを出してほしいです。PRはmerge直前に出してほしくて、そうでない場合はDraft PRとしてください。

これは先のブランチ名指定と重なるけど自分フォークからPRしてるのと(draft pr出来るのか🤔)、issue,prのprってissue上のpr(feat)かと思ってたから、そうじゃなくこういうPull Request用途でも差異ないし.github上でいいよね？って確認した感じ
なので一旦全て課題解決したら再度PRする予定

> ちょっと前のissue templateをイメージしていて、その場合記載されていると「書かなきゃ」と思ってしまうかなと思ったのですが、今はform形式で表示してくれるのですね。

まぁ正直開発メンバー的にそれなりに理解してそうだから軽く説明すれば各々すぐ理解すると思うから厳密である必要はないと思ってる。なんならテンプレートも正直不足があれば都度対応程度でいいかなーとも

2024-08-21 16:36 UTC, oginoshikibu requested changes
ちょっと長文になってしまいましたが、チーム開発のかなり重要な部分なので読んで納得してもらえるとありがたいです。

# コメント返信

> まぁ正直開発メンバー的にそれなりに理解してそうだから軽く説明すれば各々すぐ理解すると思うから厳密である必要はないと思ってる。

僕含め全員、「それなりに理解してそう」は偽だと思っています。
それぐらいチーム開発と技術を理解しているは別物という理解です。

> なんならテンプレートも正直不足があれば都度対応程度でいいかなーとも

これ完全に同意です。

2024-08-21 16:36 UTC, oginoshikibu commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +labels: ["bug"]
まず大前提として、「プロジェクト管理にタスク管理ツールは必要」という認識なのですが、問題ないですか？

タスク管理ツールの目的は色々ありますが、一番大きいものはコミュニケーションコストの低下だと思っています。
チーム開発では極論コミュニケーションがゼロであることが理想であり、非同期的な進行をすべきです。
コミュニケーションは一見何か進捗が出ているようで、複数人の時間を奪うにもかかわらず生産性はゼロです。
勿論チームビルディング的な文脈でのコミュニケーションは、インナーワークライフの向上により生産性の大きな上昇が見込めるため、可能な範囲で増やすことが合理的とされます。
ただ、それ以外の細かな確認や相談はドキュメント上で行うことが理想だと言われています。
そのためタスク管理ツールを用いて、プロジェクトや各個人の進捗を可視化します。（timesもその一環です）

上記理由から、MTGやチャット、質問を中心としたタスク運用は出来るだけ避けたい気持ちがあります。
ただ、例示した「学祭についての相談」などはセキュリティ的な観点が優位となり、クローズドの方がよいというのは正しいと思います。少し極端な例を挙げてしまいました。

githubが見にくいは同意できますが、他ツールでの運用だと不慣れメンバーに追加でアプリ使用方法を習得してもらう必要があり、そこの負担を避けたいという理由でgithub issuesでタスク管理を行うと決定しました。

話がそれてしまいました。疑問に戻ると「議論してからfeatにして、タスク切り出しを行うべきでは」でした。
僕の考えとしては、「議論してから」の部分もタスクとして扱い、1個人にAssigneesを割り振りある程度の結論を出してもらい、それをreview的に議論すべきだと考えています。
チーム開発が発足して実感してもらえていると思いますが、featにするまでのstepはかなりコストが高く、featとなってからの方が楽まであります（SIerはfeatにするまでが仕事なので、1つの職業名になるぐらいには大変です）
よって、bag, feat以外の物も必要であると考えています。

2024-08-21 16:36 UTC, oginoshikibu commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +          - 例: fixed #123
それはfeature_request.ymlについてなので、別ファイルの話ですね

2024-08-22 11:39 UTC, 1m-N00b commented
> 僕含め全員、「それなりに理解してそう」は偽だと思っています。
それぐらいチーム開発と技術を理解しているは別物という理解です。

これはPRやissueの話。だからテンプレートに不備等あっても各々が対応してくれるだろうという

> 長文の前文

言ってることは会社の上でのエンジニアなら十分正論で間違いないとは理解してるんだけど如何せん僕含めて非同期で作業推進出来るほどの能力はないと見てるからコミュニケーションベースの方がいいんじゃないと思った感じ　現にテンプレート作成ですら齟齬があるし

> タスク管理の話

タスク管理ツールは必須。その上でfeat,bug以外のtemplateだけど、何が欲しいのかまだ理解出来ていない。
(先の例の#22みたいなfeatまで持っていく系の議論メイン系なら態々テンプレートにしなくても良くないと思ってる　理由は、それをするのは大半がPMかフロント乃至バックが始まった時の統括者だろうから)

2024-08-25 09:43 UTC, oginoshikibu commented
> これはPRやissueの話。だからテンプレートに不備等あっても各々が「〇〇書きたいんですが何処に書けば」とか「〇〇書くこと無いので「なし」と記述しときました」等対応してくれるだろうという

なるほど……確かにそういった部分はちゃんとやってくれる気がしました。
僕が読み違えてましたすみません🙇🙇

> 言ってることは会社の上でのエンジニアなら十分正論で間違いないとは理解してるんだけど如何せん僕含めて非同期で作業推進出来るほどの能力はないと見てるからコミュニケーションベースの方がいいんじゃないと思った感じ 

全体が数名以下だったらコミュニケーションベースって成り立つと思うんですけど、それ以上は結構きついんじゃないかと重いっている派です……。将来的に絶対に人の入れ替わりがありますし、「非同期を諦めない意思」を持ち続けたいとは思っています。

あと、立ち上げ時期なので非同期の悪い所が見えやすくなってしまっているよな～とも思ってます。これについては僕があんまり意思表明をしていないのが悪いので、明日全体共有します！！

> あとこれは余談だけどプライベートな話題をオープン上でどう避けて書くのかが難しい(例えば自身の〇〇での経験では、...みたいな話題)

これは確かにそうですね……。まあここについてはうまいことやっていくしかないと思います。
（これは自戒なのですが、僕も明確な根拠なくお気持ちで意見を発することがありますが、これって結局技術力が不足しているから経験・お気持ちになってしまっているのだなと感じています。#24 での認証回りの議論などまさにそうで、qq8244353 のように技術的な裏どりを取って示しています。本当はこうすべきなのですが、難しいです……(´・ω・｀)。とりあえず僕は本PJでは技術パートについては出来るだけ他人の力を借りて何とかしていこうと思います……。）

> タスク管理ツールは必須。その上でfeat,bug以外のtemplateだけど、何が欲しいのかまだ理解出来ていない。 (先の例の#22みたいなfeatまで持っていく系の議論メイン系なら態々テンプレートにしなくても良くないと思ってる　理由は、それをするのは大半がPMかフロント乃至バックが始まった時の統括者だろうから)

これはissueを一覧として欲しい & 別に統括者以外がやってもよい（reviewを責任者がやる）というのが必要性です。
実際#27 はそういう形だと思いますし、何を明確化する議論 / 調査が必要なのかという点を記述する部分はissue templateとして用意してあると嬉しい気持ちがあります。

とはいえ僕も具体的にどんなテンプレートが欲しいかは、あんまりイメージできてないです……
多分ちゃんと区分立てるのは無理なので、実質その他枠として実装するのが良いと思っています。
なにかいい感じの命名があるといいのですが……難しいですね

2024-08-25 23:36 UTC, 1m-N00b commented
取り敢えず諸々一応やってみたが、どうだろう
- prを親ディレクトリの移行
- validationを概ねfalse
- feature-requestをベースにtask.ymlとしてその他として任意のテキスト枠を用意
- その他軽微な修正

2024-08-28 15:09 UTC, oginoshikibu approved these changes
LGTM！！
横道逸れた議論にも付き合ってもらいありがとうございました！！ちょっと僕も運用を想定できていない部分も多いため、気軽に修正していく方針で行きましょう。

2024-08-28 15:09 UTC, merged