Docs/environment fix
TUS-OSK/quantum-gomoku pull request #51
Opened 2024-09-29 04:43 UTC by Kousakai

## Issue Number

このプルリクが対応するIssue番号を記入してください

Close #IssueNumber

## Purpose

このプルリクの目的・内容を、一行で簡潔に記入してください

例: フロントエンド開発と並行で進行出来るように、バックエンドのLogin APIのMockを作成した。

## UI Changes

このプルリクでUIに変更がある場合は、変更前後のスクリーンショットを添付してください。

## What's changed

このプルリクで、どのような変更を行ったかを箇条書きで記入してください。
また各項目について、その想定挙動について記載してください。

例：
- login APIのMockを作成（POST: `/api/v1/users/login`）
  - ユーザー名とパスワードを受け取り、基本的には成功（ユーザーIDを含む）を返す
  - ユーザー名が`error`、もしくはパスワードが`error`の場合はエラーを返す
  - その他の異常系はリクエストボディの不正な形式の場合のみ考慮
- 上記Moc APIの仕様書を作成
  - Swagger形式で記述

## Background / Compromises

このプルリクでの対応背景や、妥協点があれば記入してください。
なおこの項目に記入する内容は、出来るだけコードのコメントにも記入してください。

例：
ログイン失敗時に関して
- ユーザーの存在確認やパスワードの一致確認など、全て統一して「ログイン失敗」扱いにしている
  - 別にするメリット：ユーザーに対してどこが間違っているのかを明示することが出来る
  - 別にするデメリット：適当なユーザー名を入力することで、ユーザーの存在確認が出来てしまう
- 今回はまだユーザー名の仕様が定まっていないため、全て統一して「ログイン失敗」扱いにしている

## Todo List

今回のプルリクはまだやっていないことや、将来やる予定の事項を記入してください。

例：
- [ ] 実処理の仕様決定とその実装
- [ ] 内部エラーなどその他の異常系

## Check List

- [ ] コード整形を行いました
- [ ] コードにドキュメントを追加しました（JSDoc、GoDocなど）
- [ ] `docker compose up`で起動し、正常に動作することを確認しました
- [ ] 全てのテストが通ることを確認しました

## Reference

関連するリンクや資料があれば記入してください

## Remark

補足事項があれば記入してください

2024-10-01 05:54 UTC, Kousakai commented
修正しておきました

2024-10-01 09:44 UTC, oginoshikibu requested changes
諸々ありがとうございます！全体的に問題ないと思います。
細かい部分をいくつかsuggestしたので、対応お願いします。
また、Descriptionで記入していない部分は削除してもらえると、読みやすくなるので助かります

2024-10-01 09:44 UTC, oginoshikibu commented on docs/0.HowToDev/01.EnvConstruction/README.md
> +アプリケーションを起動し、Accept,Skipを選択します。ターミナルの再起動を行うと、docker versionが動かせるようになります。
`docker version` は`docker`コマンドの一つでしかないため、少し適切ではないかなと思いました。
```suggestion
アプリケーションを起動し、Accept,Skipを選択します。ターミナルの再起動を行うと、`docker` コマンド（`docker version`など）が動かせるようになります。
```

2024-10-01 09:44 UTC, oginoshikibu commented on docs/0.HowToDev/01.EnvConstruction/README.md
> +古いバージョンであるとき、インストール後ターミナルの再起動が必要
文体を合わ他方が良いかなと思います。また、少し文意が取りづらく感じたので以下に変更するのはどうでしょうか。
```suggestion
`Mac`で古いバージョンが存在するときに`homebrew`版をインストールした場合、インストール後ターミナルの再起動が必要です。
```

2024-10-01 09:44 UTC, oginoshikibu commented on docs/0.HowToDev/01.EnvConstruction/README.md
> +`devcontainer`内で開発を行うことにより、実行環境と開発環境を一致させることができます。
引用が途切れています
```suggestion
> `devcontainer`内で開発を行うことにより、実行環境と開発環境を一致させることができます。
```

2024-10-01 09:44 UTC, oginoshikibu commented on docs/0.HowToDev/01.EnvConstruction/README.md
>  [公式サイト](https://www.docker.com/products/docker-desktop/)よりインストールしてください。
「インストール時に正しいCPUを選択するよう注意喚起する」がこの部分の変更の目的なので、以下のようにした方が分かりやすいのではないでしょうか
```suggestion
`Mac`の場合は`Docker Desktop`を使います。
`windows`でも使えますが、`WSL` + `Docker Desktop`を動かそうとするとメモリ消費が激しく、16GBでも足りない場合があります。

[公式サイト](https://www.docker.com/products/docker-desktop/)よりインストールしてください。ここで、自分のPCのCPUの種類に合ったものを選択するよう注意してください。
```

2024-10-01 09:44 UTC, oginoshikibu commented on docs/0.HowToDev/01.EnvConstruction/README.md
>  ## 3. Project Initialization
ついでにこの部分の変更もお願いしてもよいでしょうか？Dockerの起動方法の誘導がまだどこにも書いていないので……
```suggestion
## 3. Project Initialization

`Docker`の起動方法については、`backend/README.md``frontend/README.md`にそれぞれ記載があります。
```

2024-10-03 15:30 UTC, Kousakai reviewed
訂正しました

2024-10-10 06:19 UTC, oginoshikibu commented on docs/0.HowToDev/01.EnvConstruction/README.md
>  ## 3. Project Initialization
すみません。上記提案例で変更してもらったかと思いますが、下に記載のcloneについての方が上に来るのが自然だと思ったため、そこと入れ替えてもらえますか？？

2024-10-10 09:02 UTC, oginoshikibu commented on docs/0.HowToDev/01.EnvConstruction/README.md
> +古いバージョンであるとき、インストール後ターミナルの再起動が必要
表記通り修正しました！

2024-10-10 09:07 UTC, oginoshikibu commented on docs/0.HowToDev/01.EnvConstruction/README.md
>  ## 3. Project Initialization
こちらで変更しちゃいました！

2024-10-10 09:10 UTC, oginoshikibu requested changes
一件だけtypo見つけました

2024-10-10 09:10 UTC, oginoshikibu commented on docs/0.HowToDev/01.EnvConstruction/README.md
> +`Mac`で古いバージョンが存在するときに`homebrew`板をインストールした場合、インストール後ターミナルの再起動が必要です。
typo？？
```suggestion
`Mac`で古いバージョンが存在するときに`homebrew`版をインストールした場合、インストール後ターミナルの再起動が必要です。
```

2024-10-10 09:19 UTC, oginoshikibu commented on docs/0.HowToDev/01.EnvConstruction/README.md
> +`Mac`で古いバージョンが存在するときに`homebrew`板をインストールした場合、インストール後ターミナルの再起動が必要です。
僕がやっちゃいました

2024-10-10 09:20 UTC, oginoshikibu approved these changes
よいと思います！！ありがとうございました！！

2024-10-10 09:25 UTC, merged